### PR TITLE
Different Luigi

### PR DESCRIPTION
**Pull request by 0vxs**
In this, its just the Same Exact SMW CO OP, except for Luigi...

### CODE REVIEW

**Comment by rhelmot** [comment]
Hi! I'm having a hard time understanding what you want here. Can you explain what you wanted to change?

Usually the way contributions on github work is that you make edits that change one of my files and then you submit the changes. It looks like these are some changes to `dma.asm`, so it should be submitted as such. If you click on the "files changed" tab at the top of this page, you can see that you just added a new file named `different-luigi` instead of editing `dma.asm`.

Furthermore, from actually examining the changes to `dma.asm` manually, I don't know what you're trying to do. It looks like you've changed some of the dma to hdma? You've also commented out the preprocessor defines which normally allow you to switch between normal luigi, separate luigi graphics, and the 3p simplified graphics mode. I would like to keep these switches.

**Comment by 0vxs** [comment]
Sorry, i just wanted to have the other SNES Luigi, not the SNES Mario body
for Luigi, the SNES Luigi body for Luigi, I'm not talking about the SMAS
Luigi. Here I'll show u Two Pictures of the Small and Big Sprites im
talking about:

**Comment by rhelmot** [comment]
I don't see any pictures?

**Comment by XBloonyX** [comment]
noobish, my friend, what he wants is for luigi to have different images, like those of luigi of super mario all stars

**Comment by rhelmot** [comment]
god nobody has called me that in years

the project already supports that. if you set `!SEPERATEGFX = 1` in [co-op.asm](https://github.com/rhelmot/smw-coop/blob/master/co-op.asm#L18) it'll use the [`separate_2p.bin`](https://github.com/rhelmot/smw-coop/blob/master/graphics/seperate_2p.bin) graphics.

**Comment by XBloonyX** [comment]
yes I know, but I think it would be easier for that "1" or "0" if you change it to "true" or "false" doing this

!true = 1
!false = 0

! SEPARATEGFX = !True

:D

**Comment by rhelmot** [comment]
you should go bug the developer of asar to add true and false as keywords then ;)

**Comment by XBloonyX** [comment]
that's something that I could try

**Pull request closed without merging**
